add options attribute, bpmn can be customized
bpmn-io/vue-bpmn pull request #8
Opened 2021-03-19 09:30 UTC by meterXu

2021-03-19 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bpmn-io/vue-bpmn?pullRequest=8) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bpmn-io/vue-bpmn?pullRequest=8) before we can accept your contribution.<br/><hr/>**isaac** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bpmn-io/vue-bpmn?pullRequest=8) it.</sub>

2021-03-19 09:53 UTC, pinussilvestrus reviewed
Thanks for your contribution 👏 

Before we can merge this can you make sure to
* update your commit(s) to a single one fitting our [commit message guidelines](https://www.conventionalcommits.org/)

> feat: add options

* sign the [CLA](https://github.com/bpmn-io/vue-bpmn/pull/8#issuecomment-802686484)

Besides, I'd love to see a minimal example how this new configuration feature could be used in a Vue application. Can you maybe provide some by updating the `README`.md or the [example](https://github.com/bpmn-io/vue-bpmn/tree/master/example)?

2021-03-19 09:53 UTC, pinussilvestrus commented on package.json
> +  "version": "0.2.3",
Let's not update the package version manually. We do that when we release via `np` in an orderly manner.

2021-03-19 09:53 UTC, pinussilvestrus commented on src/index.vue
> +      },this.options)
Until we don't have linting in place for this project: let's add some space here

> }, this.options)

2021-03-19 09:53 UTC, pinussilvestrus commented on src/index.vue
> +      const _options = Object.assign({
we mix `const` and `var` here. Let's not do this.

2021-03-19 09:53 UTC, pinussilvestrus commented on src/index.vue
> +        type:Object
```suggestion
      options: {
        type: Object
```

2021-03-19 10:01 UTC, nikku commented on src/index.vue
> +        type:Object
We should consider documenting this, too.

2021-03-23 02:13 UTC, meterXu commented on package.json
> +  "version": "0.2.3",
ok

2021-03-23 02:50 UTC, meterXu commented on package.json
> +  "version": "0.2.3",
Okay, you can refer to this example
https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension

2021-03-23 11:45 UTC, nikku commented on README.md
> +    }
Missing `,`.

2021-03-23 11:46 UTC, nikku requested changes
Looking good, overall.

2021-03-24 07:31 UTC, merged